### ISSUE TITLE
Error introduced in login form

### ISSUE THREAD

**Issue by obsidianspork** [6-11-c/group-project#4]
An unhandled error is being thrown after connecting to the database and attempting to run a check on the submitted username/password, here's the code that implements this:

```js
router.post(
  "/login",
  (req, res, next) => {
    console.log('routes/user.js login: ', req.body);
    next();
  },
  passport.authenticate('local'), (req, res) => {
    console.log(`User logged in: ${req.user}`);
    let userInfo = {
      username: req.user.username
    };
    res.send(userInfo);
  }
)
```

And the error being thrown in the shell:

```
Connected to mLab
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: Illegal arguments: string, undefined
    at Object.bcrypt.compareSync (/Users/davidc/dev/woz-u/swd109_group_final/group-project/node_modules/bcryptjs/dist/bcrypt.js:265:19)
    at model.checkPassword (/Users/davidc/dev/woz-u/swd109_group_final/group-project/db/models/User/User.js:21:19)
    at User.findOne (/Users/davidc/dev/woz-u/swd109_group_final/group-project/passport/localStrategy.js:16:17)
    at /Users/davidc/dev/woz-u/swd109_group_final/group-project/node_modules/mongoose/lib/model.js:4236:16
    at process.nextTick (/Users/davidc/dev/woz-u/swd109_group_final/group-project/node_modules/mongoose/lib/query.js:2053:28)
    at process._tickCallback (internal/process/next_tick.js:61:11)
Emitted 'error' event at:
    at /Users/davidc/dev/woz-u/swd109_group_final/group-project/node_modules/mongoose/lib/model.js:4238:13
    at process.nextTick (/Users/davidc/dev/woz-u/swd109_group_final/group-project/node_modules/mongoose/lib/query.js:2053:28)
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by dcoy** [comment]
This is closed with commit [3187d4](https://github.com/6-11-c/group-project/commit/3187d4d3413346c0959056c53a9872d5005830ba)
